# Configuration file for `prek`, a git hook framework written in Rust.
# See https://prek.j178.dev for more information.
#:schema https://www.schemastore.org/prek.json

default_install_hook_types = [
  "pre-commit",
  "commit-msg"
]

[[repos]]
repo = "https://github.com/compilerla/conventional-pre-commit"
rev = "v4.3.0"
hooks = [
  {
    id = "conventional-pre-commit",
    stages = ["commit-msg"]
  }
]

[[repos]]
repo = "https://github.com/pre-commit/pre-commit-hooks"
rev = "v5.0.0"
hooks = [
  { id = "trailing-whitespace" },
  { id = "end-of-file-fixer" },
  { id = "check-yaml", args = ["--allow-multiple-documents"] },
  { id = "check-added-large-files" },
  { id = "no-commit-to-branch", args = ["--branch", "main"] }
]

[[repos]]
repo = "https://github.com/gitleaks/gitleaks"
rev = "v8.28.0"
hooks = [
  { id = "gitleaks" }
]
