name: Gitleaks

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  gitleaks:
    permissions:
      contents: read
    uses: $/.github/workflows/gitleaks.yml
