name: Run Actionlint

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  actionlint:
    permissions:
      contents: read
    uses: $/.github/workflows/actionlint.yml
