name: Zizmor

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  security-events: write

jobs:
  zizmor:
    permissions:
      security-events: write
    uses: ./.github/workflows/zizmor.yml
