name: Run Commitlint

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  pull-requests: read # required to fetch PR metadata

jobs:
  commitlint:
    permissions:
      contents: read
      pull-requests: read # required to fetch PR metadata
    uses: $/.github/workflows/commitlint.yml
