name: UV Audit

on:
  workflow_call:

permissions:
  contents: read

jobs:
  uv-audit:
    name: Run uv audit
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout Code
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262  # v4
        with:
          persist-credentials: false

      - name: Install uv
        uses: astral-sh/setup-uv@887a942a15af3a76af60a41585cb34b1beafc99c  # v5
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Run uv audit
        run: uv audit
