name: Zizmor

on:
  workflow_call:

jobs:
  zizmor:
    name: Run Zizmor
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Zizmor
        uses: zizmorcore/zizmor-action@v0.6.4
        with:
          version: latest
